[package]
name = "set-filter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
path ="src/main.rs"
name = "sf"

[dependencies]
hashbrown = "0.11.2"
structopt = "0.3.22"
